version: '3.8'

services:
  app:
    command: ["make", "dev"]
    entrypoint: []
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "0.0.0.0:8080:8080"
    volumes:
      - ./app:/app

  caddy:
    depends_on:
      - app
    image: caddy:latest
    volumes:
      - ./services/caddy:/etc/caddy
      - caddy_data:/data
      - caddy_config:/config
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"


volumes:
  caddy_data:
  caddy_config: