version: '3.8'

services:
  app:
    depends_on:
      db:
        condition: service_healthy
    image: danil0919/devops-for-developers-project-74
    env_file:
      - .env
    build: 
      context: .
      dockerfile: Dockerfile.production
    environment:
      - NODE_ENV=${NODE_ENV}
    container_name: app
    command: ["make", "test"]

  db:
    image: postgres:13-alpine
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"

volumes:
  db_data: