FROM node:20.12.2-alpine3.19
WORKDIR /app

RUN apk add --no-cache \
  python3 \
  make \
  g++ \
  gcc \
  musl-dev \
  sqlite-dev 

# Важно для кеширования слоев
COPY app/package*.json ./
RUN npm ci

COPY app .

EXPOSE 8080
ENV NODE_ENV=production
RUN make build

CMD make test