version: '3.8'

services:
  app:
    command: ["make", "dev"]
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "0.0.0.0:8080:8080"
    volumes:
      - app:/app
      - node_modules:/app/node_modules
  
  caddy:
    depends_on:
      - app
    image: caddy:latest
    volumes:
      - ./services/caddy:/etc/caddy
      - caddy_data:/data
      - caddy_config:/config
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"

volumes:
  app:
  node_modules:
  caddy_data:
  caddy_config: